apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Dankook1!
        - name: LC_ALL
          value: C.UTF-8
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-config
          items:
          - key: initdb.sql
            path: initdb.sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  initdb.sql: |
    SET GLOBAL binlog_format = 'ROW';
    CREATE DATABASE IF NOT EXISTS zeppelin;
    USE zeppelin;

    CREATE TABLE students (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30),
    score INT);

    INSERT INTO students (name, score) VALUES
    ('Alice', 90), ('Bob', 85), ('Charlie', 78), ('David', 95), ('Eva', 82);
